name: 10. Workflow Call Using Inputs Demo 

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  workflow-caller:
    uses: ./.github/workflows/10_workflow-call-inputs-2.yml
    with:
      version: 6.0.x
          

