name: 12. Define and Use Job Outputs

on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.date }}
      output2: ${{ steps.step2.outputs.name }}
    steps:
      - name: Setting Output 1
        id: step1
        run: echo "date=$(date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"

      - name: Setting Output 2
        id: step2
        run: echo "name=$(uname -o)" >> $GITHUB_OUTPUT
        
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Use Outputs from Job 1
        run: |
          echo "Output 1 from job1: ${{ needs.job1.outputs.output1 }}"
          echo "Output 2 from job1: ${{ needs.job1.outputs.output2 }}"