name: 6. Using contexts to access variables

on: workflow_dispatch

env:
  DAY_OF_WEEK: Friday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Happy Weekend!!!
    steps:
      - name: Print Variables
        if: ${{ env.DAY_OF_WEEK == 'Friday' }}
        env:
          First_Name: Vignesh
        run: |
          echo "Hey $First_Name. Today is $DAY_OF_WEEK!"
          echo "${{ env.Greeting }}"
